ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import set_language

from . import views

urlpatterns = [
	path('', views.homepage, name='home'),
	path('error/', views.errorpage, name='error'),
    path('admin/', admin.site.urls),
	path('about/', views.aboutpage),
	path('match/', include('match.urls')),
	path('ranking/', include('ranking.urls')),
	path('login/', include('login.urls')),
	path('users/', include('users.urls')),
	path('tournaments/', include('tournaments.urls')),
	path('set_language/', set_language, name='set_language'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
	path('', views.login_user, name="login"),
	path('manual_login/', views.manual_login, name="manual_login"),
	path('callback/', views.callback, name="callback"),
	path('logout/', views.logout_user, name="logout_user"),
	path('set_email/', views.set_email, name='set_email'),
	path('set_password/', views.set_password, name='set_password'),
	path('2fa/', views.verify_2fa_code_email, name='verify2fa'),
]

match/urls.py
from django.urls import path
from . import views

app_name = 'match'

urlpatterns = [
	path('', views.gamepage, name="match"),
	path('tournament_games', views.tournament_games, name="tournament_games"),
	path('tournament_final', views.tournament_final, name="tournament_final"),
	path('finish', views.finish_tournament, name="finish"),
	path('history/<str:username>/', views.history, name="history"),
	path('save_match_ajax', views.save_match_ajax, name="save_match_ajax"),
	path('save_match_ajax_4', views.save_match_ajax_4, name="save_match_ajax_4"),
]

tournaments/urls.py
from django.urls import path
from . import views

app_name = 'tournaments'

urlpatterns = [
	path('', views.tournaments, name='tournaments'),
	path('tournament_4/', views.tournament_4, name='tournament_4'),
]
	

tournaments/models.py
from django.db import models
from users.models import CustomUser
from match.models import Match
from django.utils.translation import gettext_lazy as _

class	Tournament(models.Model):
	owner = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE, related_name='owned_tournaments')
	date = models.DateTimeField('date', auto_now_add=True)
	matches = models.ManyToManyField(Match, related_name='tournaments')
	winner = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE,  related_name='won_tournaments')

	def __str__(self):
		return f"{self.id}"

	def save(self, *args, **kwargs):
		super(Tournament, self).save(*args, **kwargs)

tournaments/views.py
from .models import Tournament
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import QuerySet
from django.conf import settings
from users.models import CustomUser
import datetime
import json

from web3 import Web3
import json

def get_hashs():
	with open('./blockchain/config.json', 'r') as file:
		data = json.load(file)
		print(data)
		return data

def set_hashs(data):
	with open('./blockchain/config.json', 'w') as file:
		son.dump(data, file, indent=4)

def get_contract():
	with open('./blockchain/hardhat/artifacts/contracts/Tournaments.sol/Tournament.json') as f:
		contract = json.load(f)
	return contract

def web3_init():
	contract = get_contract()
	web3Instance = Web3(Web3.HTTPProvider('http://hardhat:8545/'))
	Tournament = web3Instance.eth.contract(abi=contract['abi'], bytecode=contract['bytecode'])
	account = web3Instance.eth.accounts[0]
	if settings.BOOL_WEB3 == False:
		try:
			data = get_hashs()
			if data.get("HASH_NANA") == "":
				settings.TX_HASH = (Tournament.constructor().transact({'from': account}))
				data["HASH_NANA"] = str(settings.TX_HASH)
			else:
				settings.TX_HASH = data.get("HASH_NANA")

			if data.get("ADDRESS_NANA") == "":
				settings.TX_RECEIPT.append(web3Instance.eth.wait_for_transaction_receipt(settings.TX_HASH))
				settings.TX_ADDRESS = settings.TX_RECEIPT[0].contractAddress
				data["ADDRESS_NANA"] = settings.TX_ADDRESS
			else:
				settings.TX_ADDRESS = data.get("ADDRESS_NANA")

			if data.get("HASH_NANA") != "" and data.get("ADDRESS_NANA") != "":
				set_hashs(data)
				settings.BOOL_WEB3 = True
		except Exception as e:
			print(e)
			pass
	deploy_contract(web3Instance)
	return (web3Instance)

def deploy_contract(web3):
	contract = get_contract()
	settings.DEPLOYED_CONTRACT = web3.eth.contract(address=settings.TX_ADDRESS, abi=contract['abi'])
	return ()

#---------------------------------------------

def serialize_queryset(queryset: QuerySet) -> dict:
	def default(obj):
		if isinstance(obj, datetime.datetime):
			return obj.isoformat()
		raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
	return json.loads(json.dumps(list(queryset), default=default))

def set_tournament(tournament_id):
	tour = Tournament.objects.get(id=tournament_id)

	all_matches = tour.matches.all()

	object_match = []
	for match in all_matches:
		object_match.append(
			{
				"user1": match.user1.username,
				"user2": match.user2.username,
				"date": str(match.date),
				"score_user1": match.score_user1,
				"score_user2": match.score_user2,
				"winner": match.winner.username
			}
		)

	tournament_data = {
		"tournament": {
				"id": tour.id,
				"date": str(tour.date),
				"winner": tour.winner.username
			},
		"matches": object_match
	}

	object_var = json.dumps(tournament_data)
	web3 = web3_init()
	try:
		transact = settings.DEPLOYED_CONTRACT.functions.addMatch(object_var).transact({'from': web3.eth.accounts[0]})
		settings.TX_RECEIPT.append(transact)
		receipt = web3.eth.wait_for_transaction_receipt(settings.TX_HASH)
		settings.TX_RECEIPT.append(receipt)
	except Exception as e:
		print(e)
	
	print("blockchain values:", get_tournament(web3))

	return

def get_tournament(web3):
	web3 = web3_init()

	values = []
	i = 0
	while True:
		try:
			value_get = settings.DEPLOYED_CONTRACT.functions.getMatchIndex(web3.to_int(i)).call()
			if value_get == "No match found":
				break
			values.append(json.loads(value_get.replace("'", "\"")))
			i += 1
		except Exception as e:
			print(e)
			break
	return values


def tournaments(request):
	tournaments = Tournament.objects.all().order_by('-date')
	return render(request, 'tournaments/tournaments.html', { 'tournaments': tournaments })

	

def tournament_4(request):
	if request.method == 'POST':
		turns = request.POST.get('qtd-turnos')
		user = get_object_or_404(CustomUser, username=request.user.username)
		friends = user.friends.all()
		return render(request, 'tournaments/tournament_4.html', {'user': user, 'friends': friends, 'turns': turns})

tournaments/templates/tournaments/tournament_4.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans "Tournament 4 Players" %}
{% endblock %}

{% block undertitle %}
    <h2><strong class="gradient-text">{% trans "Tournament 4 Players" %}</strong></h2>
{% endblock %}

{% block content %}
<form id="game-form" method="POST" action="{% url 'match:tournament_games' %}">
	{% csrf_token %}
	<div class="tournament-bracket">
		<input type="hidden" id="turns" name="turns" value="{{ turns }}">
		<div class="round round-1">
			<div class="match">
				<div id="player1" class="player">
					<h4>{% trans "Player 1" %}</h4>
					<input type="hidden" id="player1-name" name="player1" value="{{ request.user.username }}">
					<input type="hidden" id="player1-nickname" name="player1-nickname" value="{{ request.user.nickname }}">
					<span id="player1-label">{{ request.user.nickname }}</span>
				</div>
				<img class="versus-small" src="{% static 'imgs/cross.png' %}">
				<div id="player2" class="player">
					<h4>{% trans "Player 2" %}</h4>
					<button type="button" class="small-button" id="invite-btn-2" onclick="openFriendModal(2)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player2-name" name="player2">
					<input type="hidden" id="player2-nickname" name="player2-nickname">
					<span id="player2-label"></span>
				</div>
			</div>
			<div class="winner">
				<h1 class="gradient-text">{% trans "Winner" %}</h1>
				<p>{% trans "Match 1" %}</p>
			</div>
			<div class="match">
				<img src="{% static 'imgs/championship.png' %}" width="120px" height="120px">
				<div><h2><strong class="gradient-text">{% trans "Champion!" %}</strong></h2></div>
			</div>
			<div class="winner">
				<h1 class="gradient-text">{% trans "Winner" %}</h1>
				<p>{% trans "Match 2" %}</p>
			</div>
			<div class="match">
				<div id="player3" class="player">
					<h4>{% trans "Player 3" %}</h4>
					<button type="button" class="small-button" id="invite-btn-3" onclick="openFriendModal(3)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player3-name" name="player3">
					<input type="hidden" id="player3-nickname" name="player3-nickname">
					<span id="player3-label"></span>
				</div>
				<img class="versus-small" src="{% static 'imgs/cross.png' %}">
				<div id="player4" class="player">
					<h4>{% trans "Player 4" %}</h4>
					<button type="button" class="small-button" id="invite-btn-4" onclick="openFriendModal(4)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player4-name" name="player4">
					<input type="hidden" id="player4-nickname" name="player4-nickname">
					<span id="player4-label"></span>
				</div>
			</div>
		</div>
	</div>
	<div class="tournament-button">
		<button type="submit" class="small-button" id="start-game" onclick="prepareForm()">{% trans "Start Game!" %}</button>
	</div>
</form>
<div id="friend-modal" class="modal" style="display:none;">
	<div class="modal-content">
		<span class="close-button" onclick="closeFriendModal()">×</span>
		<h3><strong class="gradient-text">{% trans "Invite a Friend" %}</strong></h3>
		<ul id="friends-list">
			{% for friend in friends %}
				<li><a href="#" onclick="selectFriend('{{ friend.username }}', '{{ friend.nickname }}', currentPlayer)"> {{ friend.nickname }} </a></li>
			{% empty %}
				<li>{% trans "You still don't have any friends." %}</li>
				<li>{% trans "You Loser!" %}</li>
			{% endfor %}
		</ul>
		<button class="small-button" onclick="closeFriendModal()">{% trans "Close" %}</button>
	</div>
</div>
{% endblock %}

{% block content2 %}
<style>
    .tournament-bracket {
        width: 100%;
    }

	.tournament-button {
		margin-bottom: 50px;
	}

	.versus-small {
		width: 20px;
		height: 20px;
		align-items: center;	
	}

    .round {
        display: flex;
        flex-direction: row;
        align: center;
		justify-content: space-between;
		gap: 80px;
        align-items: center;
    }

    .match {
        display: flex;
		flex-direction: column;
        align-items: center;
        width: 100%;
		margin-bottom: 20px;	

    }

	#player1, #player3 {
		margin-bottom: 20px;
	}

    .player {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 70%;
        padding: 20px;
        text-align: center;
    }

	.winner h1{
		font-family: 'Dosis', sans-serif;
		font-weight: bold;
	}

</style>

<script>
	let selectedPlayers = [];

	function openFriendModal(playerId) {
		currentPlayer = playerId;
		document.getElementById('friend-modal').style.display = 'block';
	}

	function closeFriendModal() {
		document.getElementById('friend-modal').style.display = 'none';
	}

	function selectFriend(username, nickname, playerId) {
		if (selectedPlayers.includes(username)) {
			alert('This user was already selected for another match.');
			return;
		}

		selectedPlayers.push(username);
		
		document.getElementById(`player${playerId}-name`).value = username;
		document.getElementById(`player${playerId}-nickname`).value = nickname;
		document.getElementById(`player${playerId}-label`).innerText = nickname;
		document.getElementById(`invite-btn-${playerId}`).style.display = 'none';

		removeFriendFromList(username);

		closeFriendModal();
	}

	function removeFriendFromList(username) {
		const friendListItems = document.querySelectorAll('#friends-list li a');

		friendListItems.forEach(item => {
			if (item.getAttribute('onclick').includes(username)) {
				item.parentElement.remove();
			}
		});
	}
</script>
{% endblock %}

tournaments/templates/tournaments/tournaments.html
{% extends 'layout.html' %}
{% load static%}
{% load i18n%}

{% block title %}
	{% trans Tournaments %}
{% endblock %}

{% block undertitle %}
	<img src="{% static 'imgs/trophy.png'%}" class="ranking-image"></img><br>
	<h1><strong class="gradient-text">Tournaments History</strong></h1>
{% endblock %}

{% block content %}
{% endblock %}

{% block content2 %}
	<section>
		<div class="history">
			<table class="history-table">
				<thead>
					<tr>
						<th>{% trans "Id" %}</th>
						<th>{% trans "Owner" %}</th>
						<th>{% trans "Date" %}</th>
						<th>{% trans "Winner" %}</th>
					</tr>
				</thead>
				<tbody>
					{% for tournament in tournaments %}
					<tr>
						<td>{{ tournament.id }}</td>
						<td>{{ tournament.owner }}</td>
						<td>{{ tournament.date }}</td>
						<td>{{ tournament.winner }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</section>
{% endblock %}