ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import set_language

from . import views

urlpatterns = [
	path('', views.homepage, name='home'),
	path('error/', views.errorpage, name='error'),
    path('admin/', admin.site.urls),
	path('about/', views.aboutpage),
	path('match/', include('match.urls')),
	path('ranking/', include('ranking.urls')),
	path('login/', include('login.urls')),
	path('users/', include('users.urls')),
	path('tournaments/', include('tournaments.urls')),
	path('set_language/', set_language, name='set_language'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
	path('', views.login_user, name="login"),
	path('manual_login/', views.manual_login, name="manual_login"),
	path('callback/', views.callback, name="callback"),
	path('logout/', views.logout_user, name="logout_user"),
	path('set_email/', views.set_email, name='set_email'),
	path('set_password/', views.set_password, name='set_password'),
	path('2fa/', views.verify_2fa_code_email, name='verify2fa'),
]

match/urls.py
from django.urls import path
from . import views

app_name = 'match'

urlpatterns = [
	path('', views.gamepage, name="match"),
	path('tournament_games', views.tournament_games, name="tournament_games"),
	path('tournament_final', views.tournament_final, name="tournament_final"),
	path('finish', views.finish_tournament, name="finish"),
	path('history/<str:username>/', views.history, name="history"),
	path('save_match_ajax', views.save_match_ajax, name="save_match_ajax"),
	path('save_match_ajax_4', views.save_match_ajax_4, name="save_match_ajax_4"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('profile/<str:username>/', views.user_profile, name='profile'),
	path('add-friend/<str:username>/', views.send_friend_request, name='send_friend_request'),
	path('friends/', views.view_friends, name='view_friends'),
	path('add-friend-modal/<str:username>/', views.add_friend_modal, name='add_friend_modal'),
	path('play/<str:username>/', views.wanna_play, name='wanna_play'),
	path('play/local/<str:username>/', views.local_play, name='local_play'),
	path('play/tournament/<str:username>/', views.tournament_play, name='tournament_play'),
]

match/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from users.models import CustomUser

class	Match(models.Model):
	user1 = models.ForeignKey(CustomUser, related_name='matches_as_user1', on_delete=models.CASCADE)
	user2 = models.ForeignKey(CustomUser, related_name='matches_as_user2', on_delete=models.CASCADE)

	date = models.DateTimeField('date', auto_now_add=True)

	score_user1 = models.IntegerField('score player 1', default=0)
	score_user2 = models.IntegerField('score player 2', default=0)

	is_tournament = models.BooleanField(default=False)

	@property
	def	winner(self):
		if self.score_user1 > self.score_user2:
			return self.user1
		elif self.score_user2 > self.score_user1:
			return self.user2
		return None

	def	clean(self):
		if self.user1 == self.user2:
			raise ValidationError(_("Player 1 and Player 2 must be different users."))

	def	save(self, *args, **kwargs):
		self.clean()
		super().save(*args, **kwargs)

	class	Meta:
		constraints = [
			models.UniqueConstraint(fields=['user1', 'user2', 'date'], name='unique_match'),
		]

match/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Q
from users.models import CustomUser
from tournaments.models import Tournament
from tournaments.views import set_tournament
from .models import Match
import json
from django.db import transaction


def save_match_ajax(request):
	if request.method == 'POST':
		try:
			data = json.loads(request.body)
			user1 = data.get('user1')
			user2 = data.get('user2')
			score_user1 = data.get('score_user1')
			score_user2 = data.get('score_user2')

			usera = CustomUser.objects.get(username=user1)
			userb = CustomUser.objects.get(username=user2)

			match = Match.objects.create(
				user1=usera,
				user2=userb,
				score_user1=score_user1,
				score_user2=score_user2
			)
			match.save()

			return JsonResponse({'status': 'success', 'match_id': match.id})
		except Exception as e:
			return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
	else:
		return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)


def save_match_ajax_4(request):
	if request.method == 'POST':
		try:
			data = json.loads(request.body)
			user1 = data.get('user1')
			user2 = data.get('user2')
			user3 = data.get('user3')
			user4 = data.get('user4')
			score_user1 = data.get('score_user1')
			score_user2 = data.get('score_user2')
			score_user3 = data.get('score_user3')
			score_user4 = data.get('score_user4')

			usera = CustomUser.objects.get(username=user1)
			userb = CustomUser.objects.get(username=user2)
			userc = CustomUser.objects.get(username=user3)
			userd = CustomUser.objects.get(username=user4)

			match1 = Match.objects.create(
				user1=usera,
				user2=userb,
				score_user1=score_user1,
				score_user2=score_user2
			)
			match1.save()

			match2 = Match.objects.create(
				user1=usera,
				user2=userd,
				score_user1=score_user1,
				score_user2=score_user4
			)
			match2.save()

			match3 = Match.objects.create(
				user1=userc,
				user2=userb,
				score_user1=score_user3,
				score_user2=score_user2
			)
			match3.save()

			match4 = Match.objects.create(
				user1=userc,
				user2=userd,
				score_user1=score_user3,
				score_user2=score_user4
			)
			match4.save()
			return JsonResponse({'status': 'success'})
		except Exception as e:
			return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
	else:
		return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)


def	gamepage(request):
	if request.method == 'POST':
		usernames = [
			request.POST.get('player1'),
			request.POST.get('player2'),
			request.POST.get('player3'),
			request.POST.get('player4'),
		]
		usernames = [username for username in usernames if username]
		
		nicknames = [
			request.POST.get('player1-nickname'),
			request.POST.get('player2-nickname'),
			request.POST.get('player3-nickname'),
			request.POST.get('player4-nickname'),
		]
		nicknames = [nickname for nickname in nicknames if nickname]

		turns = request.POST.get('qtd-turnos')

		color = request.POST.get('background')
		return render(request, 'match/game.html', {'usernames': usernames, 'nicknames': nicknames, 'turns': turns, 'color': color})
	return render(request, 'home.html')


def tournament_games(request):
	if request.method == 'POST':
		usernames = [
			request.POST.get('player1'),
			request.POST.get('player2'),
			request.POST.get('player3'),
			request.POST.get('player4'),
		]		
		nicknames = [
			request.POST.get('player1-nickname'),
			request.POST.get('player2-nickname'),
			request.POST.get('player3-nickname'),
			request.POST.get('player4-nickname'),
		]
		turns = request.POST.get('turns')
		return render(request, 'match/tournament_games.html', {'usernames': usernames, 'nicknames': nicknames, 'turns': turns})
	return render(request, 'tournaments:tournament_4')

def tournament_final(request):
	if request.method == 'POST':
		user1 = request.POST.get('match-resultA-player')
		user1 = CustomUser.objects.get(username=user1)
		
		user2 =	request.POST.get('match-resultB-player')
		user2 = CustomUser.objects.get(username=user2)
		
		score_user1 = int(request.POST.get('match-resultA-score'))
		score_user2 = int(request.POST.get('match-resultB-score'))

		match1 = Match.objects.create(user1=user1, user2=user2, score_user1=score_user1, score_user2=score_user2, is_tournament=True)

		user3 =	request.POST.get('match-resultC-player')
		user3 = CustomUser.objects.get(username=user3)
		
		user4 =	request.POST.get('match-resultD-player')
		user4 = CustomUser.objects.get(username=user4)

		score_user3 = int(request.POST.get('match-resultC-score'))
		score_user4 = int(request.POST.get('match-resultD-score'))

		match2 = Match.objects.create(user1=user3, user2=user4, score_user1=score_user3, score_user2=score_user4, is_tournament=True)
		
		winner1 = request.POST.getlist('winner1')
		winner1 = [winner for winner in winner1 if winner]
		winner2 = request.POST.getlist('winner2')
		winner2 = [winner for winner in winner2 if winner]


		winner1_nickname = winner1[0]
		winner1 = CustomUser.objects.get(nickname=winner1_nickname)

		winner2_nickname = winner2[0]
		winner2 = CustomUser.objects.get(nickname=winner2_nickname)

		owner = CustomUser.objects.get(username=user1)

		turns = int(request.POST.get('turns'))

		t = None
		try:
			with transaction.atomic():
				tournament = Tournament.objects.create(owner=owner)
				tournament.matches.add(match1, match2)
				tournament.save()
				t = tournament

		except Exception as e:
			return render(request, 'home.html')

		return render(request, 'match/tournament_final.html', {'id_tournament': t, 'turns': turns, 'user1': winner1, 'user2': winner2})
	user = get_object_or_404(CustomUser, username=user1)
	return render(request, 'users/wanna_play.html', {'user': user})

def finish_tournament(request):
	username = request.user
	user = get_object_or_404(CustomUser, username=username)
	if request.method == 'POST':
		user1 = request.POST.get('match-resultA-player')
		user1 = CustomUser.objects.get(username=user1)
		
		user2 =	request.POST.get('match-resultB-player')
		user2 = CustomUser.objects.get(username=user2)
		
		score_user1 = int(request.POST.get('match-resultA-score'))
		score_user2 = int(request.POST.get('match-resultB-score'))

		match1 = Match.objects.create(user1=user1, user2=user2, score_user1=score_user1, score_user2=score_user2, is_tournament=True)

		t = request.POST.get('tournament')
		try:
			with transaction.atomic():
				tournament = Tournament.objects.get(id=t)
				tournament.matches.add(match1)
				if (score_user1 > score_user2):
					tournament.winner = user1
				elif (score_user1 < score_user2):
					tournament.winner = user2
				tournament.save()
				set_tournament(tournament.id)
		except Exception as e:
			print(e)
			return render(request, 'home.html')
		return render(request, 'users/wanna_play.html', {'user': user})
	return render(request, 'users/wanna_play.html', {'user': user})

@login_required
def history(request, username):
	user = get_object_or_404(CustomUser, username=username)
	matches = Match.objects.filter(Q(user1=user) | Q(user2=user)).order_by('-date')
	return render(request, 'match/history.html', {'user': user, 'matches': matches})

match/templates/match/game.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}

{% block token_head %}
    <meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block title %}
    {% trans "Pong Game" %}
{% endblock %}

{% block undertitle %}
    <h1><strong class="gradient-text">{% trans "Pong Contest" %}</strong></h1>
{% endblock %}

{% block content %}
    <canvas></canvas>
    <h3><strong class="gradient-text">Instructions:</strong></h3>
    <p class="game-instructions">
    <b>{{ nicknames.0 }}:</b> Control the left player using the <strong>W and S keys</strong><br>
        <b>{{ nicknames.1 }}:</b> Control the right player using the <strong>UP and DOWN arrow keys</strong><br>
        {% if nicknames|length > 2 %}
    <b>{{ nicknames.2 }}:</b> Control the left player using the <strong>Q and A keys</strong><br>
    <b>{{ nicknames.3 }}:</b> Control the right player using the <strong>I and K keys</strong><br>
        {% endif %}
    </p>
{% endblock %}

{% block scripts %}
    <script>
        usernames = [
            '{{ usernames.0|default:"" }}',
            '{{ usernames.1|default:"" }}',
            {% if nicknames|length > 2 %},
            '{{ usernames.2|default:"" }}',
            '{{ usernames.3|default:"" }}'
            {% endif %}
        ];
        nicknames = [
            '{{ nicknames.0|default:"" }}',
            '{{ nicknames.1|default:"" }}',
            {% if nicknames|length > 2 %}
            '{{ nicknames.2|default:"" }}',
            '{{ nicknames.3|default:"" }}'
            {% endif %}
        ];
        turns = {{ turns }}
        color = '{{ color }}'
    </script>
    {% if nicknames|length == 2 %}
        <script src="{% static 'js/game.js' %}"></script>
    {% elif nicknames|length == 4 %}
        <script src="{% static 'js/game2x2.js' %}"></script>
    {% endif %}
{% endblock %}

match/templates/match/history.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}


{% block title %}
{% blocktrans with username=user.nickname %}
{{ username }}'s Matches History
{% endblocktrans %}
{% endblock %}

{% block undertitle %}
	<h2><strong class="gradient-text">{% trans "Matches History" %}</strong></h2>
{% endblock %}

{% block content %}
	
{% endblock %}

{% block content2 %}
	<h2><strong class="gradient-text">
		{% blocktrans with username=user.nickname %}
		{{ username }}'s History
		{% endblocktrans %}
	</strong></h2>
	<section>
		<div class="history">
			<table class="history-table">
				<thead>
					<tr>
						<th>{% trans "Date" %}</th>
						<th>{% trans "Player 1" %}</th>
						<th>{% trans "Player 2" %}</th>
						<th>{% trans "Score Player 1" %}</th>
						<th>{% trans "Score Player 2" %}</th>
						<th>{% trans "Winner" %}</th>
						<th>{% trans "Tournament" %}</th>

					</tr>
				</thead>
				<tbody>
					{% for match in matches %}
					<tr>
						<td>{{ match.date|date:"d/m/Y" }}</td>
						<td><a href="{% url 'users:profile' match.user1.username %}">{{ match.user1.nickname }}</a></td>
						<td><a href="{% url 'users:profile' match.user2.username %}">{{ match.user2.nickname }}</a></td>
						<td>{{ match.score_user1 }}</td>
						<td>{{ match.score_user2 }}</td>
						<td><a href="{% url 'users:profile' match.winner %}">{{ match.winner.nickname }}</a></td>
						{% if match.is_tournament is True %}
						<td><img src="{% static 'imgs/check.png' %}" width="30" height="30" alt="yes" title="yes"></img></td>
						{% else %}
						<td><img src="{% static 'imgs/cross.png' %}" width="20" height="20" alt="no" title="no"></img></td>
						{% endif %}
					</tr>
					{% endfor %}
				</tbody>
	</table>
	</div>
	</section>
{% endblock %}

match/templates/match/tournament_final.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}

{% block token_head %}
	<meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block title %}
{% trans "Tournament's Final Game" %}
{% endblock %}

{% block undertitle %}
<h2><strong class="gradient-text">{% trans "Tournament's Final Game" %}</strong></h2>

<form id="final-form" method="POST" action="{% url 'match:finish' %}">
	{% csrf_token %}
	<div class="tournament-final">
		<div>
			<h3 class="gradient-text">{% trans "Final Match" %}</h3>
			<p>{{ user1.nickname }} <img src="{% static 'imgs/cross.png' %}" class="versus-small"> {{ user2.nickname }}</p>
			<div class="match-result">
				<input type="hidden" id="match-resultA-player" name="match-resultA-player" value="{{ user1.username}}">
				<input type="hidden" id="match-resultA-score" name="match-resultA-score" placeholder="Score A" value="">
				<input type="hidden" id="match-resultB-player" name="match-resultB-player" value="{{ user2.username }}">
				<input type="hidden" id="match-resultB-score" name="match-resultB-score" placeholder="Score B" value="">
				<input type="hidden" id="winner1" name="winner1" value="">
				<input type="hidden" id="tournament" name="tournament" value="{{ id_tournament }}">
			</div>
		</div>
	</div>
	<button type="button" class="small-button" id="startButton" onclick="startMatch('{{ user1.username }}', '{{ user2.username }}', '{{ user1.nickname }}', '{{ user2.nickname }}', '{{ turns }}', '1')">
		{% trans "Start Match" %}
	</button>
	<button type="button" class="small-button" id="finalButton" onclick="prepareForm(event)" style="display: none;">{% trans "Save" %}</button>
</form>
{% endblock %}

{% block content %}
	<canvas></canvas>
{% endblock %}

{% block content2 %}
	<style>
		h2 {
			margin-bottom: 10px;
		}
		
		.tournament-first-round {
			display: flex;
			flex-direction: row;
			gap: 50px;
			margin-bottom: 10px;
		}
		.match-result {
			display: flex;
		}
		#resultContainer {
			display: none;
			position: fixed;
			z-index: 9999;
			left: 0;
			top: 0;
			width: 100%;
			height: 100%;
			overflow: auto;
			background-color: rgba(0, 0, 0, 0.5);
		}

		.versus-small {
		width: 20px;
		height: 20px;
		align-items: center;
		padding: 5px;
		vertical-align: middle;
		}

		.result-content {
			margin-bottom: 10px;
			background-color: #c3c6f1;
			margin: 15% auto;
			padding: 20px;
			border: 1px solid #858cee;
			border-radius: 10px;
			width: 30%;
			color: #040c30;
			position: relative;
		}

		.close-button {
			position: absolute;
			top: 10px;
			right: 15px;
			font-size: 28px;
			font-weight: bold;
			cursor: pointer;
		}
	</style>
{% endblock %}

{% block scripts %}
<script>
	let scriptLoaded = false;

	function prepareForm(event) {
		event.preventDefault();
		document.getElementById('final-form').submit();

	}
	
	function startMatch(username1, username2, nickname1, nickname2, turns, matchNumber) {
		const finalButton = document.getElementById('finalButton');
		finalButton.style.display = 'inline-block';

		const startButton = document.getElementById('startButton');
		startButton.style.display = 'none';


		if (scriptLoaded) {
			Game.initialize(username1, username2, nickname1, nickname2, turns, matchNumber);
			return;
		}
		scriptLoaded = true;
		const script = document.createElement('script');
		script.src = "{% static 'js/tournament_games.js' %}";
		script.onload = () => {
			Game.initialize(username1, username2, nickname1, nickname2, turns, matchNumber);
		};
		script.onerror = () => {
			scriptLoaded = false;
		};
		document.body.appendChild(script);
	}
</script>
{% endblock %}

match/templates/match/tournament_games.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}

{% block token_head %}
	<meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block title %}
{% trans "Tournament's Pong Game" %}
{% endblock %}

{% block undertitle %}
<h2><strong class="gradient-text">{% trans "Tournament's Pong Game" %}</strong></h2>

<form id="tournament4-form" method="POST" action="{% url 'match:tournament_final' %}">
	{% csrf_token %}
	<div id="resultContainer">
		<div class="result-content" id="resultContent">
			<span class="close-button" onclick="closeFriendModal()">×</span>
			<h2><strong class="gradient-text">{% trans "Final Match" %}</strong></h2>
			<p>{% trans "Prepare yourselves for the final match:" %}</p>
			<input type="text" id="winner1" class="winner-light" name="winner1" value="">
			<img src="{% static 'imgs/cross.png' %}" class="versus-small">
			<input type="text" id="winner2" class="winner-light" name="winner2" value="">
			<input type="hidden" id="turns" class="turns" name="turns" value="{{ turns }}">
			<button type="button" class="small-button" id="finalButton" onclick="prepareForm(event)">{% trans "Go to Final!" %}</button>
		</div>
	</div>
	<div class="tournament-first-round">
		<div>
			<h3 class="gradient-text">{% trans "First Match" %}</h3>
			<p>{{ nicknames.0 }} <img src="{% static 'imgs/cross.png' %}" class="versus-small"> {{ nicknames.1 }}</p>
			<button type="button" id="first-match-button" class="small-button" onclick="startMatch('{{ usernames.0 }}', '{{ usernames.1 }}', '{{ nicknames.0 }}', '{{ nicknames.1 }}', '{{ turns }}', '1')">
				{% trans "Start Match" %}
			</button>
			<div class="match-result">
				<input type="hidden" id="match-resultA-player" name="match-resultA-player" value="{{ usernames.0 }}">
				<input type="hidden" id="match-resultA-score" name="match-resultA-score" placeholder="Score A" value="">
				<input type="hidden" id="match-resultB-player" name="match-resultB-player" value="{{ usernames.1 }}">
				<input type="hidden" id="match-resultB-score" name="match-resultB-score" placeholder="Score B" value="">
				<input type="hidden" id="winner1" class="winner-dark" name="winner1" value="">
			</div>
		</div>
		<div>
		</div>
		<div>
			<h3 class="gradient-text">{% trans "Second Match" %}</h3>
			<p>{{ nicknames.2 }} <img src="{% static 'imgs/cross.png' %}" class="versus-small"> {{ nicknames.3 }}</p>
			<button type="button" id="second-match-button" class="small-button" onclick="startMatch('{{ usernames.2 }}', '{{ usernames.3 }}', '{{ nicknames.2 }}', '{{ nicknames.3 }}', '{{ turns }}', '2')">
				{% trans "Start Match" %}
			</button>
			<div class="match-result">
				<input type="hidden" id="match-resultC-player" name="match-resultC-player"value="{{ usernames.2 }}">
				<input type="hidden" id="match-resultC-score" name="match-resultC-score" placeholder="Score C" value="">
				<input type="hidden" id="match-resultD-player" name="match-resultD-player" value="{{ usernames.3 }}">
				<input type="hidden" id="match-resultD-score" name="match-resultD-score" placeholder="Score D" value="">
				<input type="hidden" id="winner2" class="winner-dark" name="winner2" value="">
			</div>			
		</div>
	</div>
	<div class="see-results">
	{% comment %} <button type="button" id="see-results" class="small-button">{% trans See Results%}</button> {% endcomment %}
	<button type="button" id="see-results" class="small-button">{% trans "See results" %}</button>
</div>
</form>
{% endblock %}

{% block content %}
	<canvas></canvas>
{% endblock %}

{% block content2 %}
	<style>
		#see-results {
			display: none;
			justify-content: center;
			align-items: center;
			margin: 0 auto;
			margin-bottom: 10px;
			}
			
		.see-results {
			display: flex;
			justify-content: center;
		}

		h2 {
			margin-bottom: 10px;
		}
		
		.tournament-first-round {
			display: flex;
			flex-direction: row;
			gap: 50px;
			margin-bottom: 10px;
		}
		.match-result {
			display: flex;
		}
		#resultContainer {
			display: none;
			position: fixed;
			z-index: 9999;
			left: 0;
			top: 0;
			width: 100%;
			height: 100%;
			overflow: auto;
			background-color: rgba(0, 0, 0, 0.5);
		}

		.versus-small {
		width: 20px;
		height: 20px;
		align-items: center;
		padding: 5px;
		vertical-align: middle;
		}

		.result-content {
			margin-bottom: 10px;
			background-color: #c3c6f1;
			margin: 15% auto;
			padding: 20px;
			border: 1px solid #858cee;
			border-radius: 10px;
			width: 30%;
			color: #040c30;
			position: relative;
		}

		.close-button {
			position: absolute;
			top: 10px;
			right: 15px;
			font-size: 28px;
			font-weight: bold;
			cursor: pointer;
		}
	</style>
{% endblock %}

{% block scripts %}
<script>
	document.addEventListener('DOMContentLoaded', function() {
	const firstMatchButton = document.getElementById('first-match-button');
	const secondMatchButton = document.getElementById('second-match-button');
	const seeResultsButton = document.getElementById('see-results');

	const matchResultA = document.getElementById('match-resultA-score');
	const matchResultB = document.getElementById('match-resultB-score');
	const matchResultC = document.getElementById('match-resultC-score');
	const matchResultD = document.getElementById('match-resultD-score');

	seeResultsButton.style.display = 'none';

	firstMatchButton.addEventListener('click', function() {
	firstMatchButton.style.display = 'none';

	matchResultA.value = '3';
	matchResultB.value = '2';
	checkMatchResults();
	});

	secondMatchButton.addEventListener('click', function() {
		secondMatchButton.style.display = 'none';
		matchResultC.value = '1';
		matchResultD.value = '4';
		checkMatchResults();
	});

	function checkMatchResults() {
		if (matchResultA.value !== '' && matchResultB.value !== '' && matchResultC.value !== '' && matchResultD.value !== '') {
			seeResultsButton.style.display = 'block';
		}
	}

	seeResultsButton.addEventListener('click', function() {
		document.getElementById('resultContainer').style.display = 'block';
		document.getElementById('resultContent').style.display = 'block';
	});

	function closeFriendModal() {
		document.getElementById('resultContainer').style.display = 'none';
		document.getElementById('resultContent').style.display = 'none';
	}

	document.querySelector('.close-button').addEventListener('click', closeFriendModal);
});

	let scriptLoaded = false;

	function prepareForm(event) {
		event.preventDefault();
		document.getElementById('tournament4-form').submit();
	}
	
	function startMatch(username1, username2, nickname1, nickname2, turns, matchNumber) {
	if (scriptLoaded) {
		Game.initialize(username1, username2, nickname1, nickname2, turns, matchNumber, function(winner, score1, score2) {
			updateMatchResults(matchNumber, score1, score2);
		});
		return;
	}
	scriptLoaded = true;
	const script = document.createElement('script');
	script.src = "{% static 'js/tournament_games.js' %}";
	script.onload = () => {
		Game.initialize(username1, username2, nickname1, nickname2, turns, matchNumber, function(winner, score1, score2) {
			updateMatchResults(matchNumber, score1, score2);
		});
	};
	script.onerror = () => {
		scriptLoaded = false;
	};
	document.body.appendChild(script);
}

function updateMatchResults(matchNumber, score1, score2) {
	if (matchNumber === '1') {
		document.getElementById('match-resultA-score').value = score1;
		document.getElementById('match-resultB-score').value = score2;
	} else if (matchNumber === '2') {
		document.getElementById('match-resultC-score').value = score1;
		document.getElementById('match-resultD-score').value = score2;
	}
	checkMatchResults();
}
</script>
{% endblock %}