ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import set_language

from . import views

urlpatterns = [
	path('', views.homepage, name='home'),
	path('error/', views.errorpage, name='error'),
    path('admin/', admin.site.urls),
	path('about/', views.aboutpage),
	path('match/', include('match.urls')),
	path('ranking/', include('ranking.urls')),
	path('login/', include('login.urls')),
	path('users/', include('users.urls')),
	path('tournaments/', include('tournaments.urls')),
	path('set_language/', set_language, name='set_language'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
	path('', views.login_user, name="login"),
	path('manual_login/', views.manual_login, name="manual_login"),
	path('callback/', views.callback, name="callback"),
	path('logout/', views.logout_user, name="logout_user"),
	path('set_email/', views.set_email, name='set_email'),
	path('set_password/', views.set_password, name='set_password'),
	path('2fa/', views.verify_2fa_code_email, name='verify2fa'),
]

match/urls.py
from django.urls import path
from . import views

app_name = 'match'

urlpatterns = [
	path('', views.gamepage, name="match"),
	path('tournament_games', views.tournament_games, name="tournament_games"),
	path('tournament_final', views.tournament_final, name="tournament_final"),
	path('finish', views.finish_tournament, name="finish"),
	path('history/<str:username>/', views.history, name="history"),
	path('save_match_ajax', views.save_match_ajax, name="save_match_ajax"),
	path('save_match_ajax_4', views.save_match_ajax_4, name="save_match_ajax_4"),
]

tournaments/urls.py
from django.urls import path
from . import views

app_name = 'tournaments'

urlpatterns = [
	path('', views.tournaments, name='tournaments'),
	path('tournament_4/', views.tournament_4, name='tournament_4'),
]
	

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('profile/<str:username>/', views.user_profile, name='profile'),
	path('add-friend/<str:username>/', views.send_friend_request, name='send_friend_request'),
	path('friends/', views.view_friends, name='view_friends'),
	path('add-friend-modal/<str:username>/', views.add_friend_modal, name='add_friend_modal'),
	path('play/<str:username>/', views.wanna_play, name='wanna_play'),
	path('play/local/<str:username>/', views.local_play, name='local_play'),
	path('play/tournament/<str:username>/', views.tournament_play, name='tournament_play'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

import os

def	user_profile_picture_path(instance, filename):
	_, ext = os.path.splitext(filename)
	return f'profile_pictures/{slugify(instance.username)}_profile_picture{ext}'

class	CustomUserManager(BaseUserManager):
	def	create_user(self, email, username, password=None, **extra_fields):
		if not username:
			raise ValueError(_('A username is needed.'))
		email = self.normalize_email(email)
		user = self.model(email=email, username=username, nickname=username, **extra_fields)
		user.set_unusable_password()
		user.save(using=self._db)
		return user

	def	create_superuser(self, email, username, password=None, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		if extra_fields.get('is_staff') is not True:
			raise ValueError(_('Superuser must have is_staff=True.'))
		if extra_fields.get('is_superuser') is not True:
			raise ValueError(_('Superuser must have is_superuser=True.'))
		return self.create_user(email, username, password, **extra_fields)

class	CustomUser(AbstractBaseUser, PermissionsMixin):
	username = models.CharField(max_length=20, unique=True)
	nickname = models.CharField(max_length=20,unique=True, null=True, blank=True)
	email = models.EmailField('email address', unique=True)

	token = models.CharField(max_length=300, blank=True, null=True)

	first_name = models.CharField('first name', max_length=30, blank=True)
	last_name = models.CharField('last name', max_length=30, blank=True)
	profile_picture = models.ImageField(upload_to=user_profile_picture_path, blank=True, null=True)

	verification_code = models.IntegerField('2fa_code', blank=True, null=True)
	is_verified = models.BooleanField('verified status', default=False)

	date_joined = models.DateTimeField('date joined', default=timezone.now)
	is_active = models.BooleanField('active', default=True)
	
	is_staff = models.BooleanField('staff status', default=False)
	is_superuser = models.BooleanField('superuser status', default=False)

	is_online = models.BooleanField(default=False)
	last_online = models.DateTimeField(default=timezone.now)
	
	friends = models.ManyToManyField('self', symmetrical=False, through='Friendship')

	objects = CustomUserManager()

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = []


	class	Meta:
		verbose_name = ('user')
		verbose_name_plural = ('users')

	def	__str__(self):
		return self.username

	def	save(self, *args, **kwargs):
		if self.pk:
			old_user = CustomUser.objects.get(pk=self.pk)
			if old_user.profile_picture and old_user.profile_picture != self.profile_picture:
				old_user.profile_picture.delete(save=False)

		super(CustomUser, self).save(*args, **kwargs)

	@property
	def	total_wins(self):
		from match.models import Match
		return Match.objects.filter(
			models.Q(user1=self, score_user1__gt=models.F('score_user2')) |
			models.Q(user2=self, score_user2__gt=models.F('score_user1'))).count()

	@property
	def	total_loses(self):
		from match.models import Match
		return Match.objects.filter(
			models.Q(user1=self, score_user1__lt=models.F('score_user2')) |
			models.Q(user2=self, score_user2__lt=models.F('score_user1'))).count()

	@property
	def	total_matches_played(self):
		from match.models import Match
		return Match.objects.filter(
			models.Q(user1=self) |
			models.Q(user2=self)).count()

	@property
	def	formatted_win_rate(self):
		total_matches = self.total_matches_played
		if total_matches > 0:
			win_rate = (self.total_wins / total_matches) * 100
			return f"{win_rate:.2f}%"
		return "N/A"

class Friendship(models.Model):
	user1 = models.ForeignKey(CustomUser, related_name='friends_initiated', on_delete=models.CASCADE)
	user2 = models.ForeignKey(CustomUser, related_name='friends_received', on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

	class	Meta:
		unique_together = ('user1', 'user2')

	def	__str__(self):
		return f"{self.user1} is friends with {self.user2}"

users/forms.py
from django import forms
from users.models import CustomUser

class	EditNicknameForm(forms.ModelForm):
	class Meta:
		model = CustomUser
		fields = ['nickname']

class	ProfilePictureForm(forms.ModelForm):
	class Meta:
		model = CustomUser
		fields = ['profile_picture']
		widgets = {
			'profile_picture': forms.FileInput(attrs={'class': 'form-control'}),
		}

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import CustomUser, Friendship
from .forms import EditNicknameForm, ProfilePictureForm
from django.contrib import messages

def	user_profile(request, username):
	user = get_object_or_404(CustomUser, username=username)
	friends = Friendship.objects.filter(user1=user).select_related('user2')
	user_friends = Friendship.objects.filter(user1=request.user).values_list('user2', flat=True)
	list_users = CustomUser.objects.exclude(id__in=user_friends).exclude(id=request.user.id)
	

	if not request.user.is_anonymous:
		is_friend = request.user.friends.filter(username=user.username).exists()

	if request.method == 'POST' and 'nickname' in request.POST:
		form = EditNicknameForm(request.POST, instance=request.user)
		if form.is_valid():
			request.user.nickname = form.cleaned_data['nickname'] or request.user.username
			request.user.save()
			return redirect('users:profile', username=username)
	elif not request.user.is_anonymous:
		form = EditNicknameForm(instance=request.user)

	if request.method == 'POST' and 'profile_picture' in request.FILES:
		picture_form = ProfilePictureForm(request.POST, request.FILES, instance=request.user)
		if picture_form.is_valid():
			picture_form.save()
			return redirect('users:profile', username=username)
	elif not request.user.is_anonymous:
		picture_form = ProfilePictureForm(instance=request.user)

	if request.method == 'POST' and 'clear_profile_picture' in request.POST:
		request.user.profile_picture = None
		request.user.save()
		return redirect('users:profile', username=username)
	elif not request.user.is_anonymous:
		picture_form = ProfilePictureForm(instance=request.user)
	total_users = CustomUser.objects.all()

	if not request.user.is_anonymous:
		context = {
			'user_info': user,
			'friends': friends,
			'is_friend': is_friend,
			'form': form,
			'picture_form': picture_form,
			'annonymous': False,
			'list_users': list_users,
			'total_users': CustomUser.objects.count(),
		}
	else:
		context = {
			'user_info': user,
			'annonymous': True,
		}
	return render(request, 'users/profile.html', context)

@login_required
def	send_friend_request(request, username):
	to_user = get_object_or_404(CustomUser, username=username)
		
	if request.user != to_user:
		friendship, created = Friendship.objects.get_or_create(user1=request.user, user2=to_user)
		if created:
			Friendship.objects.get_or_create(user1=to_user, user2=request.user)
	return redirect('users:profile', username=username)

@login_required
def	view_friends(request):
	friends = request.user.friends.all()
	return render(request, 'users/friends_list.html', {'friends': friends})

@login_required
def wanna_play(request, username):
	user = get_object_or_404(CustomUser, username=username)
	return render(request, 'users/wanna_play.html', {'user': user})

@login_required
def local_play(request, username):
	user = get_object_or_404(CustomUser, username=username)
	friends = user.friends.all()
	return render(request, 'users/local_play.html', {'user': user, 'friends': friends})


@login_required
def tournament_play(request, username):
	user = get_object_or_404(CustomUser, username=username)
	friends = user.friends.all()
	return render(request, 'users/tournament_play.html', {'user': user, 'friends': friends})

@login_required
def add_friend_modal(request, username):
	to_user = get_object_or_404(CustomUser, username=username)
	if request.user != to_user:
		friendship, created = Friendship.objects.get_or_create(user1=request.user, user2=to_user)
		if created:
			Friendship.objects.get_or_create(user1=to_user, user2=request.user)
	return redirect('users:profile', username=username)

users/templates/users/local_play.html
{% extends 'layout.html' %}
{% load i18n %}

{% block title %}
	{% trans "Play" %}
{% endblock %}

{% block undertitle %}
	<h2><strong class="gradient-text">{% trans "Local Match Settings" %}</strong></h2>
{% endblock %}

{% block content %}
	<form id="game-form" method="POST" action="{% url 'match:match' %}">
		{% csrf_token %}
		<div class="local-play">
			<div id="qtd-jogadores">
				<h3><strong class="gradient-text">{% trans "Number of Players" %}</strong></h3>
				<p>{% trans "Choose the number of players:" %}</p>
				<input type="radio" name="qtd_jogadores" value="2_jogadores" checked onclick="togglePlayers(2)">
				<label>2</label>
				<input type="radio" name="qtd_jogadores" value="4_jogadores" onclick="togglePlayers(4)">
				<label>4</label>
			</div>
			<div id="qtd-turnos">
				<h3><strong class="gradient-text">{% trans "Rounds" %}</strong></h3>
				<p>{% trans "Choose the number of rounds:" %}</p>
				<input type="radio" name="qtd-turnos" value="1" checked>
				<label>1</label>
				<input type="radio" name="qtd-turnos" value="3">
				<label>3</label>
				<input type="radio" name="qtd-turnos" value="5">
				<label>5</label>
			</div>
			<div id="game-background">
				<h3><strong class="gradient-text">{% trans "Theme" %}</strong></h3>
				<input type="radio" name="background" value="#0a0a0a" checked>
				<label>{% trans "Dark" %}</label>
				<input type="radio" name="background" value="#6f6899">
				<label>{% trans "Light" %}</label>
				<input type="radio" name="background" value="#252e59">
				<label>{% trans "Modern" %}</label>
			</div>
		</div>
		<div id="local-players">
			<h3><strong class="gradient-text">{% trans "Players" %}</strong></h3>
			<p>{% trans "Choose who is playing with you:" %}</p>
			<div class="players">
				<div id="player1" class="player">
					<h4>{% trans "Player 1" %}</h4>
					<input type="hidden" id="player1-name" name="player1" value="{{ request.user.username }}">
					<input type="hidden" id="player1-nickname" name="player1-nickname" value="{{ request.user.nickname }}">
					<span id="player1-label">{{ request.user.nickname }}</span>
				</div>
				<div id="player2" class="player">
					<h4>{% trans "Player 2" %}</h4>
					<button type="button" id="invite-btn-2" class="small-button" onclick="openFriendModal(2)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player2-name" name="player2">
					<input type="hidden" id="player2-nickname" name="player2-nickname">
					<span id="player2-label"></span>
				</div>
			</div>
			<div class="players">
				<div id="player3" class="player" style="display: none;">
					<h4>{% trans "Player 3" %}</h4>
					<button type="button" id="invite-btn-3" class="small-button"  onclick="openFriendModal(3)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player3-name" name="player3">
					<input type="hidden" id="player3-nickname" name="player3-nickname">
					<span id="player3-label"></span>
				</div>
				<div id="player4" class="player" style="display: none;">
					<h4>{% trans "Player 4" %}</h4>
					<button type="button" id="invite-btn-4" class="small-button" onclick="openFriendModal(4)">{% trans "Invite Friend" %}</button>
					<input type="hidden" id="player4-name" name="player4">
					<input type="hidden" id="player4-nickname" name="player4-nickname">
					<span id="player4-label"></span>
				</div>
			</div>
		</div>

		<div id="friend-modal" class="modal" style="display:none;">
			<div class="modal-content">
				<span class="close-button" onclick="closeFriendModal()">×</span>
				<h3><strong class="gradient-text">{% trans "Invite a Friend" %}</strong></h3>
				<ul id="friends-list">
					{% for friend in friends %}
						<li><a href="#" onclick="selectFriend('{{ friend.username }}', '{{ friend.nickname }}', currentPlayer)"> {{ friend.nickname }} </a></li>
					{% empty %}
						<li>{% trans "You still don't have any friends." %}</li>
					{% endfor %}
				</ul>
				<button class="small-button" onclick="closeFriendModal()">{% trans "Close" %}</button>
			</div>
		</div>
		<div class="start-button">
			<button type="submit" class="small-button" onclick="prepareForm()">{% trans "Start Game!" %}</button>
		</div>
	</form>
{% endblock %}

{% block scripts %}
	<script>
		function togglePlayers(qtd) {
			if (qtd === 2) {
				document.getElementById('player3').style.display = 'none';
				document.getElementById('player4').style.display = 'none';
			} else {
				document.getElementById('player3').style.display = 'block';
				document.getElementById('player4').style.display = 'block';
			}
		}

		window.onload = function() {
			togglePlayers(2);
		}

		// function openFriendModal(playerId) {
		// 	currentPlayer = playerId;
		// 	document.getElementById('friend-modal').style.display = 'block';
		// }

		// function closeFriendModal() {
		// 	event.preventDefault();
		// 	document.getElementById('friend-modal').style.display = 'none';
		// }

		// function selectFriend(username, nickname, playerId) {
		// 	document.getElementById(`player${playerId}-name`).value = username;
		// 	document.getElementById(`player${playerId}-nickname`).value = nickname;
		// 	document.getElementById(`player${playerId}-label`).innerText = nickname;
		// 	document.getElementById(`invite-btn-${playerId}`).style.display = 'none';
		// 	closeFriendModal();
		// }

		let selectedPlayers = [];

	function openFriendModal(playerId) {
		currentPlayer = playerId;
		document.getElementById('friend-modal').style.display = 'block';
	}

	function closeFriendModal() {
		document.getElementById('friend-modal').style.display = 'none';
	}

	function selectFriend(username, nickname, playerId) {
		if (selectedPlayers.includes(username)) {
			alert('This user was already selected for another match.');
			return;
		}

		selectedPlayers.push(username);
		
		document.getElementById(`player${playerId}-name`).value = username;
		document.getElementById(`player${playerId}-nickname`).value = nickname;
		document.getElementById(`player${playerId}-label`).innerText = nickname;
		document.getElementById(`invite-btn-${playerId}`).style.display = 'none';

		removeFriendFromList(username);

		closeFriendModal();
	}

	function removeFriendFromList(username) {
		const friendListItems = document.querySelectorAll('#friends-list li a');

		friendListItems.forEach(item => {
			if (item.getAttribute('onclick').includes(username)) {
				item.parentElement.remove();
			}
		});
	}

		function prepareForm() {
			const player1 = document.getElementById('player1-name').value;
            const player2 = document.getElementById('player2-name').value;
            const player3 = document.getElementById('player3-name').value;
            const player4 = document.getElementById('player4-name').value;

            const turns = document.querySelector('input[name="qtd-turnos"]:checked').value;

            const color = document.querySelector('input[name="background"]:checked').value;

            const players = [player1, player2];
            if (document.getElementById('player3').style.display !== 'none') players.push(player3);
            if (document.getElementById('player4').style.display !== 'none') players.push(player4);

            const validPlayers = players.filter(player => player !== '');

            if (validPlayers.length < 2) {
                alert('Need at last 2 players.');
                event.preventDefault();
		}
	}
	</script>
{% endblock %}

users/templates/users/profile.html
{% extends 'layout.html' %}
{% load static%}
{% load i18n%}

{% block title %}
{% blocktrans with username=user_info.username %}
{{ username }}'s Profile
{% endblocktrans %}
{% endblock %}

{% block undertitle %}
	<h2><strong class="gradient-text">{{ user_info.first_name }} {{ user_info.last_name }}</strong></h2>
	<h2><strong>{{ user_info.nickname }}</strong></h2>
	{% if user_info == request.user %}
	<button id="change-nickname-button" class="small-button">{% trans "Change Nickname" %}</button>
	{% endif %}
	{% if user_info == request.user and request.user.is_verified == True  %}
		<div id="nickname-popup" class="popup" style="display:none;">
			<div class="popup-content">
				<span class="close-button">&times;</span>
				<form id="nickname-form" method="POST">
					{% csrf_token %}
					{{ form.as_p }}
					<button type="submit" class="small-button">{% trans "Save Changes" %}</button>
				</form>
			</div>
		</div>
		<div id="add-friends-modal" class="add-friends-modal" style="display:none;">
			<div class="add-friends-modal-content">
				<span class="close-button">&times;</span>
				<h2><strong class="gradient-text">{% trans "Add Friends" %}</strong></h2>
				<ul>
					{% for user in list_users %}
						<li>
							<a href="{% url 'users:profile' user.username %}">{{ user.nickname }}</a>
							<form method="post" action="{% url 'users:add_friend_modal' user.username %}">
								{% csrf_token %}
								<button type="submit" class="small-button">{% trans "Add Friend" %}</button>
							</form>
						</li>
					{% empty %}
						<li>{% trans "No users available. You're already friends with everyone!" %}</li>
					{% endfor %}
				</ul>
				<button class="small-button close-modal-button">{% trans "Close" %}</button>
			</div>
		</div>
		<div id="profile-picture-popup" class="popup" style="display:none;">
			<div class="photo-popup-content">
				<span class="close-button">&times;</span>
				<form id="profile-picture-form" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ picture_form.as_p }}
					<button type="submit" name="clear_profile_picture" class="small-button">{% trans "Delete Profile Photo" %}</button>
					<button type="submit" class="small-button">{% trans "Update Profile Photo" %}</button>
				</form>
			</div>
		</div>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="rpg-profile-container">
		<div class="profile-image-section">
			{% if user_info.profile_picture %}
				<img src="{{ user_info.profile_picture.url }}" alt="Profile Picture" class="profile-image">
			{% else %}
				<img src="{% static 'imgs/banana.png' %}" alt="Default Profile Picture" class="profile-image">
			{% endif %}
			<div class="username"><b>{{ user_info.username }}</b></div>
			{% if user_info == request.user %}
				<button id="change-picture-button" class="small-button">{% trans "Change Photo" %}</button>
			{% endif %}
		</div>
		<div class="profile-header">
			<div class="profile-stats-section">
				<h2><b>{% trans "Statistics" %}</b></h2>
				<div class="stats">
					<table class="stats-table">
						<thead>
							<tr>
								<th>{% trans "Matches" %}</th>
								<th>{% trans "Wins" %}</th>
								<th>{% trans "Losses" %}</th>
								<th>{% trans "% Wins" %}</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>{{ user_info.total_matches_played }}</td>
								<td>{{ user_info.total_wins }}</td>
								<td>{{ user_info.total_loses }}</td>
								<td>{{ user_info.formatted_win_rate }}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class ="history">
				<button class="small-button" onclick="window.location.href='{% url 'match:history' user_info.username %}'">{% trans "Matches History" %}</button>
			</div>
		</div>
{% if annonymous == False and request.user.is_verified %}
<div class="friends-section">
	<h2><strong>{% trans "Friends" %}</strong></h2>
	<ul>
		{% for friend in friends %}
			<li>
				<a href="{% url 'users:profile' friend.user2.username %}">{{ friend.user2.nickname }}</a>
				{% if friend.user2.is_online %}
					<span class="online-status online">● Online</span>
				{% else %}
					<span class="online-status offline">● Offline</span>
				{% endif %}
			</li>
		{% empty %}
			<li>{% trans "You still don't have any friends." %}</li>
		{% endfor %}
	</ul>

	{% if user_info == request.user %}
		<button class="small-button" id="open-add-friends-modal">{% trans "Add Friends" %}</button>
	{% endif %}
	{% if user_info != request.user and not is_friend and annonymous == False and request.user.is_verified %}
	<form method="post" action="{% url 'users:send_friend_request' user_info.username %}">
		{% csrf_token %}
		<button type="submit" class="small-button">{% trans "Add Friend" %}</button>
	</form>
{% endif %}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
	<script>
		const changeNicknameButton = document.getElementById('change-nickname-button');
		const nicknamePopup = document.getElementById('nickname-popup');
		const closeButton = document.querySelector('.close-button');

		changeNicknameButton.addEventListener('click', () => {
		nicknamePopup.style.display = 'block';
		});

		closeButton.addEventListener('click', () => {
		nicknamePopup.style.display = 'none';
		});
	</script>
	<script>
		document.addEventListener('DOMContentLoaded', function() {
			const changePictureButton = document.getElementById('change-picture-button');
			const profilePicturePopup = document.getElementById('profile-picture-popup');
			const closeProfilePicturePopup = profilePicturePopup.querySelector('.close-button');

			changePictureButton.addEventListener('click', function() {
				profilePicturePopup.style.display = 'block';
			});

			closeProfilePicturePopup.addEventListener('click', function() {
				profilePicturePopup.style.display = 'none';
			});

			window.addEventListener('click', function(event) {
				if (event.target === profilePicturePopup) {
					profilePicturePopup.style.display = 'none';
				}
			});
		});
	</script>
	<script>
		document.addEventListener('DOMContentLoaded', function() {
			const changePictureButton = document.getElementById('change-picture-button');
			const profilePicturePopup = document.getElementById('profile-picture-popup');
			const closeProfilePicturePopup = profilePicturePopup.querySelector('.close-button');
	
			changePictureButton.addEventListener('click', function() {
				profilePicturePopup.style.display = 'block';
			});
	
			closeProfilePicturePopup.addEventListener('click', function() {
				profilePicturePopup.style.display = 'none';
			});
	
			window.addEventListener('click', function(event) {
				if (event.target === profilePicturePopup) {
					profilePicturePopup.style.display = 'none';
				}
			});
	
			const openModalButton = document.getElementById("open-add-friends-modal");
			const addFriendsModal = document.getElementById("add-friends-modal");
			const closeAddFriendsModalButton = addFriendsModal.querySelector(".close-button");
			const closeModalButton = document.querySelector(".close-modal-button");
	
			if (openModalButton) {
				openModalButton.addEventListener("click", function() {
					addFriendsModal.style.display = "block";
				});
			}
	
			if (closeAddFriendsModalButton) {
				closeAddFriendsModalButton.addEventListener("click", function() {
					addFriendsModal.style.display = "none";
				});
			}
	
			if (closeModalButton) {
				closeModalButton.addEventListener("click", function() {
					addFriendsModal.style.display = "none";
				});
			}
	
			window.addEventListener("click", function(event) {
				if (event.target === addFriendsModal) {
					addFriendsModal.style.display = "none";
				}
			});
		});
	</script>
{% endblock %}

users/templates/users/tournament_play.html
{% extends 'layout.html' %}
{% load static%}
{% load i18n%}

{% block title %}
	{% trans "Play" %}
{% endblock %}

{% block undertitle %}
	<h2><strong class="gradient-text">{% trans "Tournament Settings" %}</strong></h2>
{% endblock %}

{% block content %}
	<form id="tournament-form" method="POST">
		{% csrf_token %}
		<div class="tournament-play">
			<div id="qtd-jogadores">
				<h3><strong class="gradient-text">{% trans "Number of Players" %}</strong></h3>
				<p>{% trans "Choose the number of players:" %}</p>
				<input type="radio" name="qtd-jogadores" value="4" checked>
				<label>4</label>
			</div>
			<div id="qtd-turnos">
				<h3><strong class="gradient-text">{% trans "Rounds" %}</strong></h3>
				<p>{% trans "Choose the number of rounds:" %}</p>
				<input type="radio" name="qtd-turnos" value="1" checked>
				<label>1</label>
				<input type="radio" name="qtd-turnos" value="3">
				<label>3</label>
				<input type="radio" name="qtd-turnos" value="5">
				<label>5</label>
			</div>
		</div>
		<div>
			<button type="submit" class="small-button" onclick="prepareForm()">{% trans "Invite Players!" %}</button>
		</div>
	</form>
{% endblock %}

{% block scripts %}
	<script>
		function prepareForm() {
			const form = document.getElementById('tournament-form');
			form.action = "{% url 'tournaments:tournament_4' %}";
		}
	</script>
{% endblock %}

users/templates/users/wanna_play.html
{% extends 'layout.html' %}
{% load static%}
{% load i18n%}

{% block title %}
	{% trans "Play" %}
{% endblock %}

{% block undertitle %}
	<h2><span class="gradient-text"><b>{% trans "Play" %}</b></span></h2>
{% endblock %}

{% block content %}
	{% trans "Choose your playing mode:" %} <br><br><br>
	<div class="play-container">
		<div class="play-column">
			<h3>Casual</h3>
			<a href="{% url 'users:local_play' user.username %}" class="btn-play">{% trans "Local game" %}</a>
		</div>
		<div id="play-torneio">
			<div class="play-column">
			<h3>{% trans "Tournament" %}</h3>
			<a href="{% url 'users:tournament_play' user.username %}" class="btn-play">{% trans "Create game" %}</a>
			</div>
		</div>
	</div>
{% endblock %}