ft_transcendence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import set_language

from . import views

urlpatterns = [
	path('', views.homepage, name='home'),
	path('error/', views.errorpage, name='error'),
    path('admin/', admin.site.urls),
	path('about/', views.aboutpage),
	path('match/', include('match.urls')),
	path('ranking/', include('ranking.urls')),
	path('login/', include('login.urls')),
	path('users/', include('users.urls')),
	path('tournaments/', include('tournaments.urls')),
	path('set_language/', set_language, name='set_language'),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
	path('', views.login_user, name="login"),
	path('manual_login/', views.manual_login, name="manual_login"),
	path('callback/', views.callback, name="callback"),
	path('logout/', views.logout_user, name="logout_user"),
	path('set_email/', views.set_email, name='set_email'),
	path('set_password/', views.set_password, name='set_password'),
	path('2fa/', views.verify_2fa_code_email, name='verify2fa'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('profile/<str:username>/', views.user_profile, name='profile'),
	path('add-friend/<str:username>/', views.send_friend_request, name='send_friend_request'),
	path('friends/', views.view_friends, name='view_friends'),
	path('add-friend-modal/<str:username>/', views.add_friend_modal, name='add_friend_modal'),
	path('play/<str:username>/', views.wanna_play, name='wanna_play'),
	path('play/local/<str:username>/', views.local_play, name='local_play'),
	path('play/tournament/<str:username>/', views.tournament_play, name='tournament_play'),
]

templates/about.html
{% extends "layout.html" %}
{% load i18n %}

{% block title %}
	Bananateam - 42
{% endblock %}

{% block undertitle %}
	<h1><span class="gradient-text"><b>BANANATEAM</b></span></h1>
{% endblock %}

{% block content %}
	<div class="story">
		<p>
			<b>{% trans "First things first..." %}</b><br>
			{% trans "Why banana?" %}<br>
			{% trans "Well, during our coding sessions, Rodrigo told us about a game in which the only goal is to click on images of bananas as much as one can." %}<br>
			{% trans "We couldn't believe so many people would waste their time on a game like that, but at the same time, we became obsessed with the ideia. After that, we started naming everything banana or some variation." %}<br><br>
			<b>{% trans "Now, the team:" %}</b>
		</p>
	</div>

	<div class="container">
		<div class="row">
			<div class="column">
				<a href="https://profile.intra.42.fr/users/csantos-" target="_blank">
					<img src="../static/imgs/csantos-.png" alt="csantos-" class="avatar" title="Clarissa">
				</a>
			</div>
			<div class="column">
				<p>
					<b>csantos- | Clarissa Santos Crisóstomo</b><br>
					{% trans "Natural of São Paulo, Clarissa is a cadet at 42 São Paulo since February 2021." %}<br>
					{% trans "It is rumored she was a diplomat in another life #diplomatique." %}</p>
					<ul class="icon-about">
						<li class="li-about">
							<a href="https://www.linkedin.com/in/clarissa-crisostomo" title="LinkedIn" target="_blank" class="link-about">
								<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-linkedin" viewBox="0 0 16 16">
									<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
								</svg>
								</a>
						</li>
						<li class="li-about"><a href="https://github.com/clacrisostomo/" title="GitHub" target="_blank">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-github" viewBox="0 0 16 16">
							<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
						</svg>
						</a>
						</li>
						</ul>
				
			</div>
		</div>
		<div class="row">
			<div class="column">
				<a href="https://profile.intra.42.fr/users/fmoreira" target="_blank">
					<img src="../static/imgs/fmoreira.png" alt="fmoreira" class="avatar" title="Felipe">
				</a>
			</div>
			<div class="column">
				<p>
					<b>fmoreira | Felipe Moreira Yorgos</b><br>
					{% trans "Natural of São Paulo, Felipe is a cadet at 42 São Paulo since May 2021." %}<br>
					{% trans "He is a very good friend of the worldly famous Mike Migrations." %}</p>
				</p>
				<ul class="icon-about">
				<li class="li-about">
				<a href="https://www.linkedin.com/in/felipe-yorgos-893518183" title="LinkedIn" target="_blank" class="link-about">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-linkedin" viewBox="0 0 16 16">
					<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
				</svg>
				</a>
				</li>
				<li class="li-about"><a href="https://github.com/Feemoyo" title="GitHub" target="_blank" class="link-about">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-github" viewBox="0 0 16 16">
					<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
				</svg>
				</a>
				</li>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="column">
				<a href="https://profile.intra.42.fr/users/rferrero" target="_blank">
					<img src="../static/imgs/rferrero.jpeg" alt="rferrero" class="avatar" title="Rodrigo">
				</a>
			</div>
			<div class="column">
				<p>
					<b>rferrero | Rodrigo Ferrero Navarro</b><br>
					{% trans "Natural from Santos, Rodrigo is a cadet at 42 São Paulo since July 2021." %}<br>
					{% trans "He can only code well if he listens to Careless Whisper by George Michael." %}</p>
					<ul class="icon-about">
					<li class="li-about">
					<a href="https://www.linkedin.com/in/roferrero" title="LinkedIn" target="_blank" class="link-about">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-linkedin" viewBox="0 0 16 16">
							<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
						</svg>
						</a>
						</li>
						<li class="li-about"><a href="https://github.com/rofnavarro" title="GitHub" target="_blank" class="link-about">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#858cee" class="bi bi-github" viewBox="0 0 16 16">
							<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
						</svg>
						</a>
						</li>
						</ul>
				</p>
			</div>
		</div>
	</div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}

{% block content %}
	<h2><span class="gradient-text"><b>{% trans "Welcome to Transcendencenana!" %}</b></span></h2>
	<br>
	<p>{% trans "Transcendencenana is a platform where you can play Pong with your friends!" %}</p>
	{% if not user.is_verified %}
	<p>{% trans "Please log in so you can start:" %}<br><br></p>
	<button class="login-button" onclick="window.location.href='/login/'">
		<img src="../static/imgs/Logo42saopaulo.png" class="button-icon"> {% trans "Sign in with 42" %}</button>
	<button class="login-button" onclick="window.location.href='/login/manual_login/'">
		<img src="../static/imgs/person.png" class="button-icon"> {% trans "Login with Username and Password" %}</button>
	{% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block token_head %}
	{% endblock %}
	<title>
		{% block title %}
			Transcendencenana
		{% endblock %}
	</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap" rel="stylesheet">
	<link rel="icon" type="image/x-icon" href="{% static 'imgs/favicon.ico' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
	<header>
		<h1><span class="gradient-text"><b>TRANSCENDENCENANA</b></span></h1>
		<div class="flags">
			<ul>
				<li>
					<form action="{% url 'set_language' %}" method="post">
						{% csrf_token %}
						<input name="next" type="hidden" value="{{ request.path }}">
						<input type="hidden" name="language" value="en">
						<button type="submit" class="flag-nav-icon">
							<img src="{% static 'imgs/usa-flag.png' %}" class="flag-icon"> English
						</button>
					</form>
				</li>
				<li>
					<form action="{% url 'set_language' %}" method="post">
						{% csrf_token %}
						<input name="next" type="hidden" value="{{ request.path }}">
						<input type="hidden" name="language" value="pt-br">
						<button type="submit" class="flag-nav-icon">
							<img src="{% static 'imgs/brazil-flag.png' %}" class="flag-icon"> Português
						</button>
					</form>
				</li>
			</ul>
		</div>
		
		
		
		
		
	<nav>
		<div class="nav-buttons">
			<ul>
			<li class="navbar"><a href="/">
				<img src="{% static 'imgs/house.png' %}" class="nav-icon"> Home
			</a></li>
			<li class="navbar"><a href="/about">
				<img src="{% static 'imgs/banana1.png' %}" class="nav-icon"> {% trans "About" %}
			</a></li>
		{% if user.is_verified %}
		{% url 'users:wanna_play' user.username as wanna_play_url %}
			<li class="navbar"><a href="{{ wanna_play_url }}">
				<img src="{% static 'imgs/joystick.png' %}" class="nav-icon"> {% trans "Play" %}
			</a></li>
		{% endif %}
			<li class="navbar"><a href="/ranking">
				<img src="{% static 'imgs/champion.png' %}" class="nav-icon"> Ranking
			</a></li>
			<li class="navbar"><a href="/tournaments">
				<img src="{% static 'imgs/trophy.png' %}" class="nav-icon"> {% trans "Tournaments" %}
			</a></li>
		</ul>
		</div>

			<div class="nav-logout">
			<ul class="nav-logout">
			{% if user.is_verified and user.is_authenticated == True %}
				{% url 'users:profile' user.username as profile_url %}
				<li class="nav-logout"><a href="{{ profile_url }}">
				<img src="{% static 'imgs/user.png' %}" class="nav-icon"> {% trans "Profile" %}
				</a></li>
				<li class="nav-logout"><a href="{% url 'login:logout_user' %}">
				<form action="{% url 'login:logout_user' %}" method="POST">
					{% csrf_token %}
					<button type="submit" class="button-logout"><img src="{% static 'imgs/logout.png' %}" class="nav-icon"> Logout</i></button>
				</form>
				</a></li>
				</ul>
			{% endif %}
		</div>
	</nav>
	</header>

	<undertitle>
		{% block undertitle %}
		{% endblock %}
	</undertitle>
	<main>		
		{% block content %}
		{% endblock %}
		{% block content2 %}
		{% endblock %}
	</main>
	{% block scripts %}
	{% endblock %}
</body>
</html>